
const OLD_DB = {
    url: 'https://nvnbqoapevtntrrvuihd.supabase.co/rest/v1',
    key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52bmJxb2FwZXZ0bnRycnZ1aWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMDMyODYsImV4cCI6MjA4Njc3OTI4Nn0.2Z0JD53Wb80eWblln_J9QHVg5ty6FC6rZD_cO58TSaU'
};

const NEW_DB = {
    url: 'https://ypqxygurmglwjowygpcl.supabase.co/rest/v1',
    key: 'sb_publishable_Rb1YMM3MtK8mjZjpL0ji0g_WDQfi3QI'
};

async function migrate(tableName) {
    console.log(`🚀 Start migration for table: ${tableName}...`);

    // 1. Fetch from Old DB
    const getResponse = await fetch(`${OLD_DB.url}/${tableName}?select=*`, {
        headers: {
            'apikey': OLD_DB.key,
            'Authorization': `Bearer ${OLD_DB.key}`
        }
    });

    if (!getResponse.ok) {
        throw new Error(`Failed to fetch from old DB [${tableName}]: ${getResponse.statusText}`);
    }

    const data = await getResponse.json();
    console.log(`📦 Fetched ${data.length} records from ${tableName}.`);

    if (data.length === 0) {
        console.log(`⚠️ No data to migrate for ${tableName}.`);
        return;
    }

    // 2. Insert into New DB
    // We remove the 'id' if it's auto-generated to avoid conflicts, or keep it if we want to preserve history.
    // Given the previous schema.sql uses 'generated by default as identity', we can keep IDs if we want.
    // However, if we want to be safe and avoid "duplicate key" errors if the new DB already has some data,
    // we might want to check. But since the user said "Success. No rows returned", it's likely empty.

    const postResponse = await fetch(`${NEW_DB.url}/${tableName}`, {
        method: 'POST',
        headers: {
            'apikey': NEW_DB.key,
            'Authorization': `Bearer ${NEW_DB.key}`,
            'Content-Type': 'application/json',
            'Prefer': 'return=representation'
        },
        body: JSON.stringify(data)
    });

    if (!postResponse.ok) {
        const errorDetail = await postResponse.text();
        throw new Error(`Failed to insert into new DB [${tableName}]: ${postResponse.statusText} - ${errorDetail}`);
    }

    console.log(`✅ Successfully migrated ${data.length} records to ${tableName}!`);
}

async function run() {
    try {
        await migrate('services');
        await migrate('appointments');
        console.log('✨ Migration completed successfully!');
    } catch (error) {
        console.error('❌ Migration failed:', error.message);
    }
}

run();
