-- Copy and paste this into the SQL Editor in your Supabase dashboard

create table public.services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price integer not null
);

create table public.appointments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client text not null,
  service text not null,
  date text not null,
  time text not null,
  price integer not null,
  worker text not null,
  status text not null default 'pending'
);

-- Turn on Realtime for these tables
alter publication supabase_realtime add table public.services;
alter publication supabase_realtime add table public.appointments;

-- Enable public access (since we are not using Supabase Auth yet)
alter table public.services enable row level security;
alter table public.appointments enable row level security;

create policy "Enable read access for all users" on public.services for select using (true);
create policy "Enable insert access for all users" on public.services for insert with check (true);
create policy "Enable update access for all users" on public.services for update using (true);
create policy "Enable delete access for all users" on public.services for delete using (true);

create policy "Enable read access for all users" on public.appointments for select using (true);
create policy "Enable insert access for all users" on public.appointments for insert with check (true);
create policy "Enable update access for all users" on public.appointments for update using (true);
create policy "Enable delete access for all users" on public.appointments for delete using (true);
